# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "allxone"
main = "api/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-04-01"

[observability]
enabled = true

[assets]
binding = "ASSETS"
not_found_handling = "single-page-application"
directory = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "react-fullstack-db"
database_id = "364b441a-445d-4fbd-8ada-1e0b479de581"

# R2 Bucket để lưu ảnh
[[r2_buckets]]
binding = "IMAGES"
bucket_name = "react-fullstack-images"

[placement]
mode = "smart"

[ai]
binding = "AI"

[vars]
JWT_SECRET = "kOIu0O//qZ7JP++tc7GSBBUmvdw+Fcm7sx/D533H0JQ="
JWT_EXPIRES_IN = "900" 

upload_source_maps = true

